### ISSUE TITLE
Topic without leading backslash doesn't show up

### ISSUE THREAD

**Issue by zxm2164** [IOT-DSA/dslink-java-mqtt#2]
If a topic does not have a leading backslash, the client makes the connection, but the data does not show up in DGLux.

**Comment by JurisPuchin** [comment]
I am assuming you mean forward slash "/", as back slashes are not typically used in MQTT.

Topics with a leading slash are different from those without. Make sure your are sending to and receiving from the same address. In my testing, both work.

From the HiveMQTT website:
> It is allowed to use a leading forward slash in MQTT, for example /myhome/groundfloor/livingroom. But that introduces a unnecessary topic level with a zero character at the front. That should be avoided, because it doesn’t provide any benefit and often leads to confusion.

https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

I have fixed the way we parse the address to better represent this in the data node tree. Topics staring with a leading slash will be under the / node.
